import 'package:dino_manager/dino.dart';

final List<Dino> items = [
  Dino("Тьюррет", "Артоплевра", Gender.male, 150),
  Dino("Дондер", "Большерогий олень", Gender.male, 150),
  Dino("Мурчаль", "Диплодок", Gender.male, 150),
  Dino("Шипуля", "Анкилозавр", Gender.male, 150),
  Dino("Проксима", "Мегалозавр", Gender.male, 150),
  Dino("Вигглитуфф", "Дедикурус", Gender.male, 150),
  Dino("Ашира", "Тиранозавр", Gender.male, 150),
  Dino("Гена", "Саркозух", Gender.male, 150),
  Dino("Артеф (Ex)", "Анкилозавр", Gender.male, 150),
  Dino("Камиль", "Мореллатопс", Gender.male, 150),
  Dino("Маунтин", "Бронтозавр", Gender.male, 150),
  Dino("Армор", "Карбонемис", Gender.male, 150),
  Dino("Бло", "Карбонемис", Gender.male, 150),
  Dino("Варута", "Карбонемис", Gender.male, 150),
  Dino("Арло", "Диплодок", Gender.male, 150),
  Dino("Флэйм", "Тиранозавр", Gender.male, 150),
  Dino("Туя", "Кентрозавр", Gender.male, 150),
  Dino("Шелл", "Карбонемис", Gender.male, 150),
  Dino("Ухура", "Халикотерий", Gender.male, 150),
  Dino("Таркин", "Карнотавр", Gender.male, 150),
  Dino("Селин", "Пахиринозавр", Gender.male, 150),
  Dino("Клефэйри", "Дедикурус", Gender.male, 150),
  Dino("Фобос", "Бронтозавр", Gender.male, 150),
  Dino("Пси", "Раптор", Gender.male, 150),
  Dino("Тайгер", "Птеранодон", Gender.male, 150),
  Dino("Клефэбл", "Дедикурус", Gender.male, 150),
  Dino("Доздраперма", "Бронтозавр", Gender.male, 150),
  Dino("Анка", "Лампадог ", Gender.male, 150),
  Dino("Киви", "Птеранодон", Gender.male, 150),
  Dino("Кенга", "Прокоптодон", Gender.male, 150),
];